# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymoliere/datatypes/datatypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pymoliere/datatypes/datatypes.proto',
  package='pymoliere',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n#pymoliere/datatypes/datatypes.proto\x12\tpymoliere\"0\n\x04\x44\x61te\x12\x0c\n\x04year\x18\x01 \x01(\x05\x12\r\n\x05month\x18\x02 \x01(\x05\x12\x0b\n\x03\x64\x61y\x18\x03 \x01(\x05\"/\n\x06\x41uthor\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"E\n\x07Journal\x12\x0e\n\x06volume\x18\x01 \x01(\x05\x12\r\n\x05issue\x18\x02 \x01(\x05\x12\x0c\n\x04year\x18\x03 \x01(\x05\x12\r\n\x05title\x18\x04 \x01(\t\"\xb3\x01\n\x0cPubMedRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\traw_title\x18\x02 \x01(\t\x12\x14\n\x0craw_abstract\x18\x03 \x01(\t\x12\x0f\n\x07version\x18\x04 \x01(\x05\x12\'\n\x0e\x64\x61te_completed\x18\x05 \x01(\x0b\x32\x0f.pymoliere.Date\x12\x10\n\x08language\x18\x07 \x01(\t\x12\"\n\x07\x61uthors\x18\x08 \x03(\x0b\x32\x11.pymoliere.Author')
)




_DATE = _descriptor.Descriptor(
  name='Date',
  full_name='pymoliere.Date',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='pymoliere.Date.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='month', full_name='pymoliere.Date.month', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='day', full_name='pymoliere.Date.day', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=98,
)


_AUTHOR = _descriptor.Descriptor(
  name='Author',
  full_name='pymoliere.Author',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='pymoliere.Author.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='pymoliere.Author.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=147,
)


_JOURNAL = _descriptor.Descriptor(
  name='Journal',
  full_name='pymoliere.Journal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='pymoliere.Journal.volume', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='issue', full_name='pymoliere.Journal.issue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year', full_name='pymoliere.Journal.year', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='pymoliere.Journal.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=218,
)


_PUBMEDRECORD = _descriptor.Descriptor(
  name='PubMedRecord',
  full_name='pymoliere.PubMedRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pymoliere.PubMedRecord.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_title', full_name='pymoliere.PubMedRecord.raw_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_abstract', full_name='pymoliere.PubMedRecord.raw_abstract', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='pymoliere.PubMedRecord.version', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date_completed', full_name='pymoliere.PubMedRecord.date_completed', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='language', full_name='pymoliere.PubMedRecord.language', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='authors', full_name='pymoliere.PubMedRecord.authors', index=6,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=400,
)

_PUBMEDRECORD.fields_by_name['date_completed'].message_type = _DATE
_PUBMEDRECORD.fields_by_name['authors'].message_type = _AUTHOR
DESCRIPTOR.message_types_by_name['Date'] = _DATE
DESCRIPTOR.message_types_by_name['Author'] = _AUTHOR
DESCRIPTOR.message_types_by_name['Journal'] = _JOURNAL
DESCRIPTOR.message_types_by_name['PubMedRecord'] = _PUBMEDRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Date = _reflection.GeneratedProtocolMessageType('Date', (_message.Message,), dict(
  DESCRIPTOR = _DATE,
  __module__ = 'pymoliere.datatypes.datatypes_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.Date)
  ))
_sym_db.RegisterMessage(Date)

Author = _reflection.GeneratedProtocolMessageType('Author', (_message.Message,), dict(
  DESCRIPTOR = _AUTHOR,
  __module__ = 'pymoliere.datatypes.datatypes_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.Author)
  ))
_sym_db.RegisterMessage(Author)

Journal = _reflection.GeneratedProtocolMessageType('Journal', (_message.Message,), dict(
  DESCRIPTOR = _JOURNAL,
  __module__ = 'pymoliere.datatypes.datatypes_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.Journal)
  ))
_sym_db.RegisterMessage(Journal)

PubMedRecord = _reflection.GeneratedProtocolMessageType('PubMedRecord', (_message.Message,), dict(
  DESCRIPTOR = _PUBMEDRECORD,
  __module__ = 'pymoliere.datatypes.datatypes_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.PubMedRecord)
  ))
_sym_db.RegisterMessage(PubMedRecord)


# @@protoc_insertion_point(module_scope)
