# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymoliere/config/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pymoliere/config/config.proto',
  package='pymoliere',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1dpymoliere/config/config.proto\x12\tpymoliere\"T\n\tFtpSource\x12%\n\x07\x61\x64\x64ress\x18\x01 \x01(\t:\x14\x66tp.ncbi.nlm.nih.gov\x12 \n\x07workdir\x18\x02 \x01(\t:\x0fpubmed/baseline\"i\n\rClusterConfig\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x12\n\x04port\x18\x02 \x01(\x05:\x04\x38\x37\x38\x36\x12\x1b\n\rlocal_scratch\x18\x03 \x01(\t:\x04/tmp\x12\x16\n\x0eshared_scratch\x18\x04 \x01(\t\"_\n\x0f\x43onstructConfig\x12)\n\x07\x63luster\x18\x01 \x01(\x0b\x32\x18.pymoliere.ClusterConfig\x12!\n\x03\x66tp\x18\x03 \x01(\x0b\x32\x14.pymoliere.FtpSource\"8\n\x0bQueryConfig\x12)\n\x07\x63luster\x18\x01 \x01(\x0b\x32\x18.pymoliere.ClusterConfig')
)




_FTPSOURCE = _descriptor.Descriptor(
  name='FtpSource',
  full_name='pymoliere.FtpSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='pymoliere.FtpSource.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("ftp.ncbi.nlm.nih.gov").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workdir', full_name='pymoliere.FtpSource.workdir', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("pubmed/baseline").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=128,
)


_CLUSTERCONFIG = _descriptor.Descriptor(
  name='ClusterConfig',
  full_name='pymoliere.ClusterConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='pymoliere.ClusterConfig.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='pymoliere.ClusterConfig.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=8786,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='local_scratch', full_name='pymoliere.ClusterConfig.local_scratch', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("/tmp").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shared_scratch', full_name='pymoliere.ClusterConfig.shared_scratch', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=235,
)


_CONSTRUCTCONFIG = _descriptor.Descriptor(
  name='ConstructConfig',
  full_name='pymoliere.ConstructConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='pymoliere.ConstructConfig.cluster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ftp', full_name='pymoliere.ConstructConfig.ftp', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=332,
)


_QUERYCONFIG = _descriptor.Descriptor(
  name='QueryConfig',
  full_name='pymoliere.QueryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='pymoliere.QueryConfig.cluster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=334,
  serialized_end=390,
)

_CONSTRUCTCONFIG.fields_by_name['cluster'].message_type = _CLUSTERCONFIG
_CONSTRUCTCONFIG.fields_by_name['ftp'].message_type = _FTPSOURCE
_QUERYCONFIG.fields_by_name['cluster'].message_type = _CLUSTERCONFIG
DESCRIPTOR.message_types_by_name['FtpSource'] = _FTPSOURCE
DESCRIPTOR.message_types_by_name['ClusterConfig'] = _CLUSTERCONFIG
DESCRIPTOR.message_types_by_name['ConstructConfig'] = _CONSTRUCTCONFIG
DESCRIPTOR.message_types_by_name['QueryConfig'] = _QUERYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FtpSource = _reflection.GeneratedProtocolMessageType('FtpSource', (_message.Message,), {
  'DESCRIPTOR' : _FTPSOURCE,
  '__module__' : 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.FtpSource)
  })
_sym_db.RegisterMessage(FtpSource)

ClusterConfig = _reflection.GeneratedProtocolMessageType('ClusterConfig', (_message.Message,), {
  'DESCRIPTOR' : _CLUSTERCONFIG,
  '__module__' : 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.ClusterConfig)
  })
_sym_db.RegisterMessage(ClusterConfig)

ConstructConfig = _reflection.GeneratedProtocolMessageType('ConstructConfig', (_message.Message,), {
  'DESCRIPTOR' : _CONSTRUCTCONFIG,
  '__module__' : 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.ConstructConfig)
  })
_sym_db.RegisterMessage(ConstructConfig)

QueryConfig = _reflection.GeneratedProtocolMessageType('QueryConfig', (_message.Message,), {
  'DESCRIPTOR' : _QUERYCONFIG,
  '__module__' : 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.QueryConfig)
  })
_sym_db.RegisterMessage(QueryConfig)


# @@protoc_insertion_point(module_scope)
