# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymoliere/config/config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pymoliere/config/config.proto',
  package='pymoliere',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1dpymoliere/config/config.proto\x12\tpymoliere\"U\n\tFtpSource\x12%\n\x07\x61\x64\x64ress\x18\x01 \x01(\t:\x14\x66tp.ncbi.nlm.nih.gov\x12!\n\x08\x64ir_path\x18\x02 \x01(\t:\x0fpubmed/baseline\"3\n\rClusterConfig\x12\x14\n\x0chead_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"#\n\x10\x44\x61taServerConfig\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"\xa5\x01\n\x0f\x43onstructConfig\x12)\n\x07\x63luster\x18\x01 \x01(\x0b\x32\x18.pymoliere.ClusterConfig\x12/\n\ndataserver\x18\x02 \x01(\x0b\x32\x1b.pymoliere.DataServerConfig\x12(\n\nftp_source\x18\x03 \x01(\x0b\x32\x14.pymoliere.FtpSource\x12\x0c\n\x04name\x18\x04 \x01(\t\"i\n\x0bQueryConfig\x12)\n\x07\x63luster\x18\x01 \x01(\x0b\x32\x18.pymoliere.ClusterConfig\x12/\n\ndataserver\x18\x02 \x01(\x0b\x32\x1b.pymoliere.DataServerConfig')
)




_FTPSOURCE = _descriptor.Descriptor(
  name='FtpSource',
  full_name='pymoliere.FtpSource',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='pymoliere.FtpSource.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("ftp.ncbi.nlm.nih.gov").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dir_path', full_name='pymoliere.FtpSource.dir_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("pubmed/baseline").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=129,
)


_CLUSTERCONFIG = _descriptor.Descriptor(
  name='ClusterConfig',
  full_name='pymoliere.ClusterConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='head_address', full_name='pymoliere.ClusterConfig.head_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='pymoliere.ClusterConfig.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=182,
)


_DATASERVERCONFIG = _descriptor.Descriptor(
  name='DataServerConfig',
  full_name='pymoliere.DataServerConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='pymoliere.DataServerConfig.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=219,
)


_CONSTRUCTCONFIG = _descriptor.Descriptor(
  name='ConstructConfig',
  full_name='pymoliere.ConstructConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='pymoliere.ConstructConfig.cluster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataserver', full_name='pymoliere.ConstructConfig.dataserver', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ftp_source', full_name='pymoliere.ConstructConfig.ftp_source', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pymoliere.ConstructConfig.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=387,
)


_QUERYCONFIG = _descriptor.Descriptor(
  name='QueryConfig',
  full_name='pymoliere.QueryConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cluster', full_name='pymoliere.QueryConfig.cluster', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dataserver', full_name='pymoliere.QueryConfig.dataserver', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=494,
)

_CONSTRUCTCONFIG.fields_by_name['cluster'].message_type = _CLUSTERCONFIG
_CONSTRUCTCONFIG.fields_by_name['dataserver'].message_type = _DATASERVERCONFIG
_CONSTRUCTCONFIG.fields_by_name['ftp_source'].message_type = _FTPSOURCE
_QUERYCONFIG.fields_by_name['cluster'].message_type = _CLUSTERCONFIG
_QUERYCONFIG.fields_by_name['dataserver'].message_type = _DATASERVERCONFIG
DESCRIPTOR.message_types_by_name['FtpSource'] = _FTPSOURCE
DESCRIPTOR.message_types_by_name['ClusterConfig'] = _CLUSTERCONFIG
DESCRIPTOR.message_types_by_name['DataServerConfig'] = _DATASERVERCONFIG
DESCRIPTOR.message_types_by_name['ConstructConfig'] = _CONSTRUCTCONFIG
DESCRIPTOR.message_types_by_name['QueryConfig'] = _QUERYCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FtpSource = _reflection.GeneratedProtocolMessageType('FtpSource', (_message.Message,), dict(
  DESCRIPTOR = _FTPSOURCE,
  __module__ = 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.FtpSource)
  ))
_sym_db.RegisterMessage(FtpSource)

ClusterConfig = _reflection.GeneratedProtocolMessageType('ClusterConfig', (_message.Message,), dict(
  DESCRIPTOR = _CLUSTERCONFIG,
  __module__ = 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.ClusterConfig)
  ))
_sym_db.RegisterMessage(ClusterConfig)

DataServerConfig = _reflection.GeneratedProtocolMessageType('DataServerConfig', (_message.Message,), dict(
  DESCRIPTOR = _DATASERVERCONFIG,
  __module__ = 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.DataServerConfig)
  ))
_sym_db.RegisterMessage(DataServerConfig)

ConstructConfig = _reflection.GeneratedProtocolMessageType('ConstructConfig', (_message.Message,), dict(
  DESCRIPTOR = _CONSTRUCTCONFIG,
  __module__ = 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.ConstructConfig)
  ))
_sym_db.RegisterMessage(ConstructConfig)

QueryConfig = _reflection.GeneratedProtocolMessageType('QueryConfig', (_message.Message,), dict(
  DESCRIPTOR = _QUERYCONFIG,
  __module__ = 'pymoliere.config.config_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.QueryConfig)
  ))
_sym_db.RegisterMessage(QueryConfig)


# @@protoc_insertion_point(module_scope)
