# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

# The conda env will bring along protobuf and python version
# ALL PYTHON DEPS MUST BE SPECIFIED HERE
# Look at help/write_docs.md for details
conda:
  environment: docs/environment.yaml

python:
  install:
    - method: setuptools
      path: .

# We do not require git submodules to process this
submodules:
  exclude: all

