#!/bin/bash
#PBS -q bigmem
#PBS -l select=1:ncpus=64:mem=1950gb,walltime=72:00:00
#PBS -o /dev/null
#PBS -e /dev/null
#PBS -N redis
#PBS -m be

if [[ -n $PBS_O_WORKDIR ]]; then
  cd $PBS_O_WORKDIR
fi

CONF=${1:-"moliere.redis.conf"}

~/software/redis/src/redis-server $CONF

