#!/bin/bash

DASK_SCHEDULER=$1
DASK_PORT=8786

while read WORKER; do
  echo Starting worker at $WORKER
  ssh $WORKER """
    dask-worker \
      $DASK_SCHEDULER:$DASK_PORT \
  """ >& /dev/null \
  &
done < $PBS_NODEFILE


