#!/bin/bash

PROCS=${1:-1}
THREADS=${2:-16}
MEM=${3:-60GB}

DASK_WORKER_LOCAL=/tmp/__dask__
DASK_WORKER_SHARED=/scratch4/$USER/__dask__
DASK_PORT=8786

mkdir -p $DASK_WORKER_SHARED

# Starting scheduler
dask-scheduler \
  --port $DASK_PORT \
  --local-directory $DASK_WORKER_LOCAL \
  --scheduler-file $DASK_WORKER_SHARED/scheduler.json \
  --interface ib0 \
  &

NODEFILE=$PBS_NODEFILE
if [[ ! -f "$NODEFILE" ]]; then
  NODEFILE=/home/jsybran/.nodefile
fi
if [[ ! -f "$NODEFILE" ]]; then
  echo "Must supply a nodefile"
  exit 1
fi

NUM_NODES=$(wc -l < $NODEFILE)
echo Starting on $NUM_NODES nodes

parallel \
  --sshloginfile "$NODEFILE" \
  --ungroup \
  -j 1 \
  """
    echo Starting {} on \$HOSTNAME
    dask-worker \
      $HOSTNAME:$DASK_PORT \
      --nprocs $PROCS \
      --nthreads $THREADS \
      --memory-limit $MEM \
      --local-directory $DASK_WORKER_LOCAL \
      --scheduler-file $DASK_WORKER_SHARED/scheduler.json \
      --interface ib0
  """ ::: $(seq $NUM_NODES)
