#!/bin/bash

MODULE_NAME="pymoliere"

CONDA_START=~/anaconda3/etc/profile.d/conda.sh
MODULE_GROUP=~/module_groups/$MODULE_NAME

echo $MODULE_NAME > ~/.default_module


source $CONDA_START
source $MODULE_GROUP

mkdir $LOG_DIR
dask-ssh \
  --hostfile $PBS_NODEFILE
