#!/bin/bash

DATA_BASE=/scratch4/jsybran/pymoliere_2020_01_02
MODEL_BASE=$DATA_BASE/models/point_cloud_evaluator
TRAINING_DATA=$MODEL_BASE/training_data
ENTITIES=$DATA_BASE/pytorch_biggraph/entities
EMBEDDINGS=$DATA_BASE/pytorch_biggraph/embeddings
GRAPH=$DATA_BASE/mongo_data/graph.sqlite3
#GRAPH=$DATA_BASE/mongo_data/sentence_lemma_graph.sqlite3
EMB_LOC_DB=$DATA_BASE/pytorch_biggraph/entities/embedding_location_index.sqlite3
MODEL_CKPT_DIR=$MODEL_BASE/sent_point_cloud_ckpts

mkdir -p $TRAINING_DATA
mkdir -p $MODEL_CKPT_DIR
