#!/bin/bash

source paths

python3 -m pymoliere.ml.point_cloud_evaluator                     \
  --sqlite-graph $GRAPH                                           \
  --sqlite-embedding-location $EMB_LOC_DB                         \
  --embedding-dir $EMBEDDINGS                                     \
  --entity-dir $ENTITIES                                          \
  --batch-size 256                                                \
  --mode prep                                                     \
  --training-data-dir $TRAINING_DATA                              \
  --cluster-address node2009

