#!/bin/bash

source paths

mkdir -p $TRAINING_DATA


# debug
if [[ ! -z "$1" ]]; then
  python3 -m pymoliere.ml.point_cloud_evaluator                     \
    --model-ckpt-dir $MODEL_CKPT_DIR                                \
    --sqlite-graph $GRAPH \
    --sqlite-embedding-location $EMB_LOC_DB \
    --entity-dir $ENTITIES \
    --embedding-dir $EMBEDDINGS \
    --positives-per-batch 256 \
    --neg-scramble-rate 7 \
    --transformer-layers 4 \
    --transformer-heads 8
else

  NODEFILE=$PBS_NODEFILE
  if [[ ! -f "$NODEFILE" ]]; then
    NODEFILE=/home/jsybran/.nodefile
  fi
  if [[ ! -f "$NODEFILE" ]]; then
    echo "Must supply a nodefile"
    exit 1
  fi

  NUM_NODES=$(wc -l < $NODEFILE)
  echo Starting on $NUM_NODES nodes

  parallel \
    --sshloginfile "$NODEFILE" \
    --ungroup \
    -j 1 \
    """
      python3 -m pymoliere.ml.point_cloud_evaluator                     \
        --training-data-dir $TRAINING_DATA                              \
        --model-ckpt-dir $MODEL_CKPT_DIR                                \
        --batch-size 256                                                \
        --train-num-machines $NUM_NODES
    """ ::: $(seq $NUM_NODES)
fi
