#!/bin/bash

source paths

mkdir -p $TRAINING_DATA


# debug
if [[ ! -z "$1" ]]; then
  python3 -m pymoliere.ml.point_cloud_evaluator                     \
    --training-data-dir $TRAINING_DATA                              \
    --model-ckpt-dir $MODEL_CKPT_DIR                                \
    --batch-size 16                                                 \
    --debug
else

  NODEFILE=$PBS_NODEFILE
  if [[ ! -f "$NODEFILE" ]]; then
    NODEFILE=/home/jsybran/.nodefile
  fi
  if [[ ! -f "$NODEFILE" ]]; then
    echo "Must supply a nodefile"
    exit 1
  fi

  NUM_NODES=$(wc -l < $NODEFILE)
  echo Starting on $NUM_NODES nodes

  parallel \
    --sshloginfile "$NODEFILE" \
    --ungroup \
    -j 1 \
    """
      python3 -m pymoliere.ml.point_cloud_evaluator                     \
        --training-data-dir $TRAINING_DATA                              \
        --model-ckpt-dir $MODEL_CKPT_DIR                                \
        --batch-size 512                                                \
        --train-num-machines $NUM_NODES
    """ ::: $(seq $NUM_NODES)
fi
