#!/bin/bash

source paths

mkdir -p $TRAINING_DATA

# debug
python3 -m pymoliere.ml.hypothesis_predictor                      \
  --entity-dir $ENTITIES                                          \
  --embedding-dir $EMBEDDINGS                                     \
  --sqlite-embedding-location $EMB_LOC_DB                         \
  --model-ckpt-dir $MODEL_CKPT_DIR                                \
  --batch-size 512                                                \
  --mode test \
  --test-data-dir $TEST_BENCHMARK
#else

  #NODEFILE=$PBS_NODEFILE
  #if [[ ! -f "$NODEFILE" ]]; then
    #NODEFILE=/home/jsybran/.nodefile
  #fi
  #if [[ ! -f "$NODEFILE" ]]; then
    #echo "Must supply a nodefile"
    #exit 1
  #fi

  #NUM_NODES=$(wc -l < $NODEFILE)
  #echo Starting on $NUM_NODES nodes

  #parallel \
    #--sshloginfile "$NODEFILE" \
    #--ungroup \
    #-j 1 \
    #"""
      #python3 -m pymoliere.ml.hypothesis_predictor                      \
        #--entity-dir $ENTITIES                                          \
        #--embedding-dir $EMBEDDINGS                                     \
        #--sqlite-embedding-location $EMB_LOC_DB                         \
        #--model-ckpt-dir $MODEL_CKPT_DIR                                \
        #--batch-size 1024                                               \
        #--train-num-machines $NUM_NODES
    #""" ::: $(seq $NUM_NODES)
#fi
