#!/bin/bash

source paths

mkdir -p $TRAINING_DATA

if [ -z "$1" ]; then

  NODEFILE=$PBS_NODEFILE
  if [[ ! -f "$NODEFILE" ]]; then
    NODEFILE=/home/jsybran/.nodefile
  fi
  if [[ ! -f "$NODEFILE" ]]; then
    echo "Must supply a nodefile"
    exit 1
  fi

  NUM_NODES=$(wc -l < $NODEFILE)
  echo Starting on $NUM_NODES nodes

  parallel \
    --sshloginfile "$NODEFILE" \
    --ungroup \
    -j 1 \
    """
      sleep {}
      echo Starting {}
      python3 -m pymoliere.ml.hypothesis_predictor                      \
        --entity-dir $ENTITIES                                          \
        --embedding-dir $EMBEDDINGS                                     \
        --sqlite-embedding-path $EMB_LOC_DB                             \
        --sqlite-graph-path $SEMMEDDB_GRAPH                             \
        --model-ckpt-dir $MODEL_CKPT_DIR                                \
        --positives-per-batch 400                                       \
        --neg-swap-rate 7                                               \
        --neg-scramble-rate 0                                           \
        --neighbors-per-term 10                                         \
        --test-data-dir $TEST_BENCHMARK                                 \
        --train-num-machines $NUM_NODES                                 \
        --train-fraction 0.1                                            \
        --distributed
    """ ::: $(seq $NUM_NODES)

else

    python3 -m pymoliere.ml.hypothesis_predictor                      \
      --entity-dir $ENTITIES                                          \
      --embedding-dir $EMBEDDINGS                                     \
      --sqlite-embedding-path $EMB_LOC_DB                             \
      --sqlite-graph-path $SEMMEDDB_GRAPH                             \
      --model-ckpt-dir $MODEL_CKPT_DIR                                \
      --margin 0.1 \
      --dim 512 \
      --transformer-ff-dim 1024 \
      --transformer-layers 4 \
      --transformer-heads 16 \
      --positives-per-batch 20                                        \
      --neg-swap-rate 30                                              \
      --neg-scramble-rate 10                                          \
      --neighbors-per-term 15                                         \
      --train-fraction 0.01                                           \
      --validation-fraction 0.01                                      \
      --test-data-dir $TEST_BENCHMARK

fi
