#!/bin/bash

NTHREADS=${1:-16}
echo "Starting Dask cluster with $NTHREADS threads per-node"

mkdir -p ~/.dask
cp dask.config.yaml ~/.dask/config.yaml

DASK_TMP_DIR=/scratch2/$USER/__dask__
mkdir -p $DASK_TMP_DIR
echo "temporary-directory: $DASK_TMP_DIR" >> ~/.dask/config.yaml

MODULE_NAME="pymoliere"

CONDA_START=~/anaconda3/etc/profile.d/conda.sh
MODULE_GROUP=~/module_groups/$MODULE_NAME

echo $MODULE_NAME > ~/.default_module


source $CONDA_START
source $MODULE_GROUP

dask-ssh \
  --hostfile $PBS_NODEFILE \
  --nthreads $NTHREADS
