#!/bin/bash
CONDA_START=~/anaconda3/etc/profile.d/conda.sh
MODULE_GROUP=~/module_groups/redis_dist
RAY_PORT=4545
RAY_HEAD=$HOSTNAME:$RAY_PORT
WORKER_FILE=$(mktemp)

source $CONDA_START
source $MODULE_GROUP

# Ensure that call is correct
if [[ $(grep $HOSTNAME $PBS_NODEFILE | wc -l) -ne 1 ]]; then
  echo "Must run from the head node of a PBS cluster."
  echo "Cluster workers defined in \$PBS_NODEFILE"
  exit 1
fi

echo "Launching ray head"
ray stop
ray \
  --logging-level error\
  start --head --redis-port $RAY_PORT
echo "$RAY_HEAD" > ~/.addresses/ray_head

echo "Launching ray on all workers"
grep -v $HOSTNAME $PBS_NODEFILE > $WORKER_FILE

for ADDR in $(grep -v $HOSTNAME $PBS_NODEFILE);
do {
ssh -T $ADDR << EOF
  source $CONDA_START
  source $MODULE_GROUP
  ray stop
  ray \
    --logging-level error \
    start --redis-address=$RAY_HEAD
  echo Started on $ADDR
EOF
} &
done
wait
