# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pymoliere/query/query.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pymoliere/query/query.proto',
  package='pymoliere',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1bpymoliere/query/query.proto\x12\tpymoliere\"u\n\x05Topic\x12\x31\n\x0cterm_weights\x18\x01 \x03(\x0b\x32\x1b.pymoliere.Topic.TermWeight\x12\r\n\x05index\x18\x02 \x01(\x05\x1a*\n\nTermWeight\x12\x0c\n\x04term\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x02\"}\n\x08\x44ocument\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\rtopic_weights\x18\x02 \x03(\x0b\x32\x1f.pymoliere.Document.TopicWeight\x1a,\n\x0bTopicWeight\x12\r\n\x05topic\x18\x01 \x01(\x05\x12\x0e\n\x06weight\x18\x02 \x01(\x02\"\x87\x01\n\rMoliereResult\x12\x0c\n\x04path\x18\x01 \x03(\t\x12&\n\tdocuments\x18\x02 \x03(\x0b\x32\x13.pymoliere.Document\x12 \n\x06topics\x18\x03 \x03(\x0b\x32\x10.pymoliere.Topic\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0e\n\x06target\x18\x05 \x01(\t')
)




_TOPIC_TERMWEIGHT = _descriptor.Descriptor(
  name='TermWeight',
  full_name='pymoliere.Topic.TermWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term', full_name='pymoliere.Topic.TermWeight.term', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='pymoliere.Topic.TermWeight.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=159,
)

_TOPIC = _descriptor.Descriptor(
  name='Topic',
  full_name='pymoliere.Topic',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='term_weights', full_name='pymoliere.Topic.term_weights', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='index', full_name='pymoliere.Topic.index', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TOPIC_TERMWEIGHT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=159,
)


_DOCUMENT_TOPICWEIGHT = _descriptor.Descriptor(
  name='TopicWeight',
  full_name='pymoliere.Document.TopicWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='topic', full_name='pymoliere.Document.TopicWeight.topic', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='pymoliere.Document.TopicWeight.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=286,
)

_DOCUMENT = _descriptor.Descriptor(
  name='Document',
  full_name='pymoliere.Document',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pymoliere.Document.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topic_weights', full_name='pymoliere.Document.topic_weights', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOCUMENT_TOPICWEIGHT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=286,
)


_MOLIERERESULT = _descriptor.Descriptor(
  name='MoliereResult',
  full_name='pymoliere.MoliereResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='pymoliere.MoliereResult.path', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='documents', full_name='pymoliere.MoliereResult.documents', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='topics', full_name='pymoliere.MoliereResult.topics', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='pymoliere.MoliereResult.source', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='target', full_name='pymoliere.MoliereResult.target', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=424,
)

_TOPIC_TERMWEIGHT.containing_type = _TOPIC
_TOPIC.fields_by_name['term_weights'].message_type = _TOPIC_TERMWEIGHT
_DOCUMENT_TOPICWEIGHT.containing_type = _DOCUMENT
_DOCUMENT.fields_by_name['topic_weights'].message_type = _DOCUMENT_TOPICWEIGHT
_MOLIERERESULT.fields_by_name['documents'].message_type = _DOCUMENT
_MOLIERERESULT.fields_by_name['topics'].message_type = _TOPIC
DESCRIPTOR.message_types_by_name['Topic'] = _TOPIC
DESCRIPTOR.message_types_by_name['Document'] = _DOCUMENT
DESCRIPTOR.message_types_by_name['MoliereResult'] = _MOLIERERESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Topic = _reflection.GeneratedProtocolMessageType('Topic', (_message.Message,), {

  'TermWeight' : _reflection.GeneratedProtocolMessageType('TermWeight', (_message.Message,), {
    'DESCRIPTOR' : _TOPIC_TERMWEIGHT,
    '__module__' : 'pymoliere.query.query_pb2'
    # @@protoc_insertion_point(class_scope:pymoliere.Topic.TermWeight)
    })
  ,
  'DESCRIPTOR' : _TOPIC,
  '__module__' : 'pymoliere.query.query_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.Topic)
  })
_sym_db.RegisterMessage(Topic)
_sym_db.RegisterMessage(Topic.TermWeight)

Document = _reflection.GeneratedProtocolMessageType('Document', (_message.Message,), {

  'TopicWeight' : _reflection.GeneratedProtocolMessageType('TopicWeight', (_message.Message,), {
    'DESCRIPTOR' : _DOCUMENT_TOPICWEIGHT,
    '__module__' : 'pymoliere.query.query_pb2'
    # @@protoc_insertion_point(class_scope:pymoliere.Document.TopicWeight)
    })
  ,
  'DESCRIPTOR' : _DOCUMENT,
  '__module__' : 'pymoliere.query.query_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.Document)
  })
_sym_db.RegisterMessage(Document)
_sym_db.RegisterMessage(Document.TopicWeight)

MoliereResult = _reflection.GeneratedProtocolMessageType('MoliereResult', (_message.Message,), {
  'DESCRIPTOR' : _MOLIERERESULT,
  '__module__' : 'pymoliere.query.query_pb2'
  # @@protoc_insertion_point(class_scope:pymoliere.MoliereResult)
  })
_sym_db.RegisterMessage(MoliereResult)


# @@protoc_insertion_point(module_scope)
